[package]
name = "rustboyadvance"
version = "0.1.0"
authors = ["Michel Heily <michelheily@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "*"
arm7tdmi = {path = "arm7tdmi"}

[[bin]]
name = "disassembler"
path = "src/disassembler.rs"